MOVIE RECOMMENDATION SYSTEM

QUESTION STATEMENT- It is a machine learning model which recommends movies on your movie input basis.
it follows content based model, which suggests you movies on the content or gener based.
Libraries used are, numpy,pandas,matplotlib.pyplot,os,ast, and nltk.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os

In [1]:
#fedding or imprting the csv files, movies, credits

In [2]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [3]:
movies.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,Unnamed: 20,Unnamed: 21
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,2787965087,162,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,NaN,NaN
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,961000000,169,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,NaN,NaN

In [4]:
credits.head(3)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."

In [5]:
movies.shape

(4803, 22)

In [6]:
credits.shape

(4803, 4)

In [7]:
movies.merge(credits, on = 'title')

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,status,tagline,title,vote_average,vote_count,Unnamed: 20,Unnamed: 21,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,Released,Enter the World of Pandora.,Avatar,7.2,11800,NaN,NaN,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,NaN,NaN,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,Released,A Plan No One Escapes,Spectre,6.3,4466,NaN,NaN,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.31295,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,Released,The Legend Ends,The Dark Knight Rises,7.6,9106,NaN,NaN,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,Released,"Lost in our world, found in another.",John Carter,6.1,2124,NaN,NaN,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4791,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]",...,Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,NaN,NaN,9367,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4792,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],...,Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,NaN,NaN,72766,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4793,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...",...,Released,NaN,"Signed, Sealed, Delivered",7,6,NaN,NaN,231617,"[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4794,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],...,Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7,NaN,NaN,126186,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4795,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...",...,Released,NaN,My Date with Drew,6.3,16,NaN,NaN,25975,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [8]:
movies.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,Unnamed: 20,Unnamed: 21
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,2787965087,162,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,NaN,NaN
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,961000000,169,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,NaN,NaN

In [9]:
movies = movies.merge(credits, on = 'title')

In [2]:
#merging the the credits csv file into the movies file only

In [10]:
movies.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,status,tagline,title,vote_average,vote_count,Unnamed: 20,Unnamed: 21,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,Released,Enter the World of Pandora.,Avatar,7.2,11800,NaN,NaN,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,NaN,NaN,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [11]:
movies.shape

(4796, 25)

In [12]:
movies.shape

(4796, 25)

In [13]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4796 entries, 0 to 4795
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4796 non-null   int64
 1   genres                4796 non-null   object
 2   homepage              1710 non-null   object
 3   id                    4796 non-null   int64
 4   keywords              4796 non-null   object
 5   original_language     4796 non-null   object
 6   original_title        4796 non-null   object
 7   overview              4793 non-null   object
 8   popularity            4796 non-null   object
 9   production_companies  4796 non-null   object
 10  production_countries  4796 non-null   object
 11  release_date          4795 non-null   object
 12  revenue               4796 non-null   object
 13  runtime               4794 non-null   object
 14  spoken_languages      4796 non-null   object
 15  status                4796 non-null   object
 16  tagline               3954 non-null   object
 17  title                 4796 non-null   object
 18  vote_average          4796 non-null   object
 19  vote_count            4796 non-null   object
 20  Unnamed: 20           0 non-null      float64
 21  Unnamed: 21           0 non-null      float64
 22  movie_id              4796 non-null   int64
 23  cast                  4796 non-null   object
 24  crew                  4796 non-null   object
dtypes: float64(2), int64(3), object(20)
memory usage: 936.8+ KB

In [14]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [15]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,Unnamed: 20,Unnamed: 21
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,2787965087,162,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,NaN,NaN

In [16]:
movies.shape

(4803, 22)

In [17]:
movies.merge(credits, on = 'title')

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,status,tagline,title,vote_average,vote_count,Unnamed: 20,Unnamed: 21,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,Released,Enter the World of Pandora.,Avatar,7.2,11800,NaN,NaN,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,NaN,NaN,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,Released,A Plan No One Escapes,Spectre,6.3,4466,NaN,NaN,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.31295,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,Released,The Legend Ends,The Dark Knight Rises,7.6,9106,NaN,NaN,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,Released,"Lost in our world, found in another.",John Carter,6.1,2124,NaN,NaN,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4791,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]",...,Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,NaN,NaN,9367,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4792,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],...,Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,NaN,NaN,72766,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4793,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...",...,Released,NaN,"Signed, Sealed, Delivered",7,6,NaN,NaN,231617,"[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4794,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],...,Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7,NaN,NaN,126186,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4795,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...",...,Released,NaN,My Date with Drew,6.3,16,NaN,NaN,25975,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [18]:
movies = movies.merge(credits, on = 'title')

In [19]:
movies.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,status,tagline,title,vote_average,vote_count,Unnamed: 20,Unnamed: 21,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,Released,Enter the World of Pandora.,Avatar,7.2,11800,NaN,NaN,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,NaN,NaN,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [20]:
movies.shape

(4796, 25)

In [21]:
movies['original_language']

0       en
1       en
2       en
3       en
4       en
        ..
4791    es
4792    en
4793    en
4794    en
4795    en
Name: original_language, Length: 4796, dtype: object

In [22]:
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [23]:
movies.head(3)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."

In [24]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [25]:
movies.dropna(inplace = True)

In [26]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [27]:
movies.duplicated().sum()

0

In [28]:
movies.iloc[0]['genres']

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [29]:
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [30]:
def convert(obj):
    lst = []
    for i in ast.literal_eval(obj):
        lst.append(i['name'])
        return lst

In [31]:
movies['genres'] = movies['genres'].apply(convert)

In [32]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...",[Action],"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",[Adventure],"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,[Action],"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,[Action],"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...",[Action],"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [33]:
movies['keywords'].apply(convert)

0                      [culture clash]
1                              [ocean]
2                                [spy]
3                          [dc comics]
4                     [based on novel]
                     ...
4791    [united statesâ€“mexico barrier]
4792                              None
4793                            [date]
4794                              None
4795                       [obsession]
Name: keywords, Length: 4793, dtype: object

In [34]:
movies['keywords'] = movies['keywords'].apply(convert)

In [35]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...",[Action],[culture clash],"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",[Adventure],[ocean],"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,[Action],[spy],"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,[Action],[dc comics],"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...",[Action],[based on novel],"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [36]:
ast.literal_eval(credits['cast'][0])

[{'cast_id': 242,
  'character': 'Jake Sully',
  'credit_id': '5602a8a7c3a3685532001c9a',
  'gender': 2,
  'id': 65731,
  'name': 'Sam Worthington',
  'order': 0},
 {'cast_id': 3,
  'character': 'Neytiri',
  'credit_id': '52fe48009251416c750ac9cb',
  'gender': 1,
  'id': 8691,
  'name': 'Zoe Saldana',
  'order': 1},
 {'cast_id': 25,
  'character': 'Dr. Grace Augustine',
  'credit_id': '52fe48009251416c750aca39',
  'gender': 1,
  'id': 10205,
  'name': 'Sigourney Weaver',
  'order': 2},
 {'cast_id': 4,
  'character': 'Col. Quaritch',
  'credit_id': '52fe48009251416c750ac9cf',
  'gender': 2,
  'id': 32747,
  'name': 'Stephen Lang',
  'order': 3},
 {'cast_id': 5,
  'character': 'Trudy Chacon',
  'credit_id': '52fe48009251416c750ac9d3',
  'gender': 1,
  'id': 17647,
  'name': 'Michelle Rodriguez',
  'order': 4},
 {'cast_id': 8,
  'character': 'Selfridge',
  'credit_id': '52fe48009251416c750ac9e1',
  'gender': 2,
  'id': 1771,
  'name': 'Giovanni Ribisi',
  'order': 5},
 {'cast_id': 7,
  'character': 'Norm Spellman',
  'credit_id': '52fe48009251416c750ac9dd',
  'gender': 2,
  'id': 59231,
  'name': 'Joel David Moore',
  'order': 6},
 {'cast_id': 9,
  'character': 'Moat',
  'credit_id': '52fe48009251416c750ac9e5',
  'gender': 1,
  'id': 30485,
  'name': 'CCH Pounder',
  'order': 7},
 {'cast_id': 11,
  'character': 'Eytukan',
  'credit_id': '52fe48009251416c750ac9ed',
  'gender': 2,
  'id': 15853,
  'name': 'Wes Studi',
  'order': 8},
 {'cast_id': 10,
  'character': "Tsu'Tey",
  'credit_id': '52fe48009251416c750ac9e9',
  'gender': 2,
  'id': 10964,
  'name': 'Laz Alonso',
  'order': 9},
 {'cast_id': 12,
  'character': 'Dr. Max Patel',
  'credit_id': '52fe48009251416c750ac9f1',
  'gender': 2,
  'id': 95697,
  'name': 'Dileep Rao',
  'order': 10},
 {'cast_id': 13,
  'character': 'Lyle Wainfleet',
  'credit_id': '52fe48009251416c750ac9f5',
  'gender': 2,
  'id': 98215,
  'name': 'Matt Gerald',
  'order': 11},
 {'cast_id': 32,
  'character': 'Private Fike',
  'credit_id': '52fe48009251416c750aca5b',
  'gender': 2,
  'id': 154153,
  'name': 'Sean Anthony Moran',
  'order': 12},
 {'cast_id': 33,
  'character': 'Cryo Vault Med Tech',
  'credit_id': '52fe48009251416c750aca5f',
  'gender': 2,
  'id': 397312,
  'name': 'Jason Whyte',
  'order': 13},
 {'cast_id': 34,
  'character': 'Venture Star Crew Chief',
  'credit_id': '52fe48009251416c750aca63',
  'gender': 2,
  'id': 42317,
  'name': 'Scott Lawrence',
  'order': 14},
 {'cast_id': 35,
  'character': 'Lock Up Trooper',
  'credit_id': '52fe48009251416c750aca67',
  'gender': 2,
  'id': 986734,
  'name': 'Kelly Kilgour',
  'order': 15},
 {'cast_id': 36,
  'character': 'Shuttle Pilot',
  'credit_id': '52fe48009251416c750aca6b',
  'gender': 0,
  'id': 1207227,
  'name': 'James Patrick Pitt',
  'order': 16},
 {'cast_id': 37,
  'character': 'Shuttle Co-Pilot',
  'credit_id': '52fe48009251416c750aca6f',
  'gender': 0,
  'id': 1180936,
  'name': 'Sean Patrick Murphy',
  'order': 17},
 {'cast_id': 38,
  'character': 'Shuttle Crew Chief',
  'credit_id': '52fe48009251416c750aca73',
  'gender': 2,
  'id': 1019578,
  'name': 'Peter Dillon',
  'order': 18},
 {'cast_id': 39,
  'character': 'Tractor Operator / Troupe',
  'credit_id': '52fe48009251416c750aca77',
  'gender': 0,
  'id': 91443,
  'name': 'Kevin Dorman',
  'order': 19},
 {'cast_id': 40,
  'character': 'Dragon Gunship Pilot',
  'credit_id': '52fe48009251416c750aca7b',
  'gender': 2,
  'id': 173391,
  'name': 'Kelson Henderson',
  'order': 20},
 {'cast_id': 41,
  'character': 'Dragon Gunship Gunner',
  'credit_id': '52fe48009251416c750aca7f',
  'gender': 0,
  'id': 1207236,
  'name': 'David Van Horn',
  'order': 21},
 {'cast_id': 42,
  'character': 'Dragon Gunship Navigator',
  'credit_id': '52fe48009251416c750aca83',
  'gender': 0,
  'id': 215913,
  'name': 'Jacob Tomuri',
  'order': 22},
 {'cast_id': 43,
  'character': 'Suit #1',
  'credit_id': '52fe48009251416c750aca87',
  'gender': 0,
  'id': 143206,
  'name': 'Michael Blain-Rozgay',
  'order': 23},
 {'cast_id': 44,
  'character': 'Suit #2',
  'credit_id': '52fe48009251416c750aca8b',
  'gender': 2,
  'id': 169676,
  'name': 'Jon Curry',
  'order': 24},
 {'cast_id': 46,
  'character': 'Ambient Room Tech',
  'credit_id': '52fe48009251416c750aca8f',
  'gender': 0,
  'id': 1048610,
  'name': 'Luke Hawker',
  'order': 25},
 {'cast_id': 47,
  'character': 'Ambient Room Tech / Troupe',
  'credit_id': '52fe48009251416c750aca93',
  'gender': 0,
  'id': 42288,
  'name': 'Woody Schultz',
  'order': 26},
 {'cast_id': 48,
  'character': 'Horse Clan Leader',
  'credit_id': '52fe48009251416c750aca97',
  'gender': 2,
  'id': 68278,
  'name': 'Peter Mensah',
  'order': 27},
 {'cast_id': 49,
  'character': 'Link Room Tech',
  'credit_id': '52fe48009251416c750aca9b',
  'gender': 0,
  'id': 1207247,
  'name': 'Sonia Yee',
  'order': 28},
 {'cast_id': 50,
  'character': 'Basketball Avatar / Troupe',
  'credit_id': '52fe48009251416c750aca9f',
  'gender': 1,
  'id': 1207248,
  'name': 'Jahnel Curfman',
  'order': 29},
 {'cast_id': 51,
  'character': 'Basketball Avatar',
  'credit_id': '52fe48009251416c750acaa3',
  'gender': 0,
  'id': 89714,
  'name': 'Ilram Choi',
  'order': 30},
 {'cast_id': 52,
  'character': "Na'vi Child",
  'credit_id': '52fe48009251416c750acaa7',
  'gender': 0,
  'id': 1207249,
  'name': 'Kyla Warren',
  'order': 31},
 {'cast_id': 53,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acaab',
  'gender': 0,
  'id': 1207250,
  'name': 'Lisa Roumain',
  'order': 32},
 {'cast_id': 54,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acaaf',
  'gender': 1,
  'id': 83105,
  'name': 'Debra Wilson',
  'order': 33},
 {'cast_id': 57,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acabb',
  'gender': 0,
  'id': 1207253,
  'name': 'Chris Mala',
  'order': 34},
 {'cast_id': 55,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acab3',
  'gender': 0,
  'id': 1207251,
  'name': 'Taylor Kibby',
  'order': 35},
 {'cast_id': 56,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acab7',
  'gender': 0,
  'id': 1207252,
  'name': 'Jodie Landau',
  'order': 36},
 {'cast_id': 58,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acabf',
  'gender': 0,
  'id': 1207254,
  'name': 'Julie Lamm',
  'order': 37},
 {'cast_id': 59,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acac3',
  'gender': 0,
  'id': 1207257,
  'name': 'Cullen B. Madden',
  'order': 38},
 {'cast_id': 60,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acac7',
  'gender': 0,
  'id': 1207259,
  'name': 'Joseph Brady Madden',
  'order': 39},
 {'cast_id': 61,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acacb',
  'gender': 0,
  'id': 1207262,
  'name': 'Frankie Torres',
  'order': 40},
 {'cast_id': 62,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acacf',
  'gender': 1,
  'id': 1158600,
  'name': 'Austin Wilson',
  'order': 41},
 {'cast_id': 63,
  'character': 'Troupe',
  'credit_id': '52fe48019251416c750acad3',
  'gender': 1,
  'id': 983705,
  'name': 'Sara Wilson',
  'order': 42},
 {'cast_id': 64,
  'character': 'Troupe',
  'credit_id': '52fe48019251416c750acad7',
  'gender': 0,
  'id': 1207263,
  'name': 'Tamica Washington-Miller',
  'order': 43},
 {'cast_id': 65,
  'character': 'Op Center Staff',
  'credit_id': '52fe48019251416c750acadb',
  'gender': 1,
  'id': 1145098,
  'name': 'Lucy Briant',
  'order': 44},
 {'cast_id': 66,
  'character': 'Op Center Staff',
  'credit_id': '52fe48019251416c750acadf',
  'gender': 2,
  'id': 33305,
  'name': 'Nathan Meister',
  'order': 45},
 {'cast_id': 67,
  'character': 'Op Center Staff',
  'credit_id': '52fe48019251416c750acae3',
  'gender': 0,
  'id': 1207264,
  'name': 'Gerry Blair',
  'order': 46},
 {'cast_id': 68,
  'character': 'Op Center Staff',
  'credit_id': '52fe48019251416c750acae7',
  'gender': 2,
  'id': 33311,
  'name': 'Matthew Chamberlain',
  'order': 47},
 {'cast_id': 69,
  'character': 'Op Center Staff',
  'credit_id': '52fe48019251416c750acaeb',
  'gender': 0,
  'id': 1207265,
  'name': 'Paul Yates',
  'order': 48},
 {'cast_id': 70,
  'character': 'Op Center Duty Officer',
  'credit_id': '52fe48019251416c750acaef',
  'gender': 0,
  'id': 1207266,
  'name': 'Wray Wilson',
  'order': 49},
 {'cast_id': 71,
  'character': 'Op Center Staff',
  'credit_id': '52fe48019251416c750acaf3',
  'gender': 2,
  'id': 54492,
  'name': 'James Gaylyn',
  'order': 50},
 {'cast_id': 72,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acaf7',
  'gender': 0,
  'id': 1207267,
  'name': 'Melvin Leno Clark III',
  'order': 51},
 {'cast_id': 73,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acafb',
  'gender': 0,
  'id': 1207268,
  'name': 'Carvon Futrell',
  'order': 52},
 {'cast_id': 74,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acaff',
  'gender': 0,
  'id': 1207269,
  'name': 'Brandon Jelkes',
  'order': 53},
 {'cast_id': 75,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acb03',
  'gender': 0,
  'id': 1207270,
  'name': 'Micah Moch',
  'order': 54},
 {'cast_id': 76,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acb07',
  'gender': 0,
  'id': 1207271,
  'name': 'Hanniyah Muhammad',
  'order': 55},
 {'cast_id': 77,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acb0b',
  'gender': 0,
  'id': 1207272,
  'name': 'Christopher Nolen',
  'order': 56},
 {'cast_id': 78,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acb0f',
  'gender': 0,
  'id': 1207273,
  'name': 'Christa Oliver',
  'order': 57},
 {'cast_id': 79,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acb13',
  'gender': 0,
  'id': 1207274,
  'name': 'April Marie Thomas',
  'order': 58},
 {'cast_id': 80,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acb17',
  'gender': 0,
  'id': 1207275,
  'name': 'Bravita A. Threatt',
  'order': 59},
 {'cast_id': 81,
  'character': 'Mining Chief (uncredited)',
  'credit_id': '52fe48019251416c750acb1b',
  'gender': 0,
  'id': 1207276,
  'name': 'Colin Bleasdale',
  'order': 60},
 {'cast_id': 82,
  'character': 'Veteran Miner (uncredited)',
  'credit_id': '52fe48019251416c750acb1f',
  'gender': 0,
  'id': 107969,
  'name': 'Mike Bodnar',
  'order': 61},
 {'cast_id': 83,
  'character': 'Richard (uncredited)',
  'credit_id': '52fe48019251416c750acb23',
  'gender': 0,
  'id': 1207278,
  'name': 'Matt Clayton',
  'order': 62},
 {'cast_id': 84,
  'character': "Nav'i (uncredited)",
  'credit_id': '52fe48019251416c750acb27',
  'gender': 1,
  'id': 147898,
  'name': 'Nicole Dionne',
  'order': 63},
 {'cast_id': 85,
  'character': 'Trooper (uncredited)',
  'credit_id': '52fe48019251416c750acb2b',
  'gender': 0,
  'id': 1207280,
  'name': 'Jamie Harrison',
  'order': 64},
 {'cast_id': 86,
  'character': 'Trooper (uncredited)',
  'credit_id': '52fe48019251416c750acb2f',
  'gender': 0,
  'id': 1207281,
  'name': 'Allan Henry',
  'order': 65},
 {'cast_id': 87,
  'character': 'Ground Technician (uncredited)',
  'credit_id': '52fe48019251416c750acb33',
  'gender': 2,
  'id': 1207282,
  'name': 'Anthony Ingruber',
  'order': 66},
 {'cast_id': 88,
  'character': 'Flight Crew Mechanic (uncredited)',
  'credit_id': '52fe48019251416c750acb37',
  'gender': 0,
  'id': 1207283,
  'name': 'Ashley Jeffery',
  'order': 67},
 {'cast_id': 14,
  'character': 'Samson Pilot',
  'credit_id': '52fe48009251416c750ac9f9',
  'gender': 0,
  'id': 98216,
  'name': 'Dean Knowsley',
  'order': 68},
 {'cast_id': 89,
  'character': 'Trooper (uncredited)',
  'credit_id': '52fe48019251416c750acb3b',
  'gender': 0,
  'id': 1201399,
  'name': 'Joseph Mika-Hunt',
  'order': 69},
 {'cast_id': 90,
  'character': 'Banshee (uncredited)',
  'credit_id': '52fe48019251416c750acb3f',
  'gender': 0,
  'id': 236696,
  'name': 'Terry Notary',
  'order': 70},
 {'cast_id': 91,
  'character': 'Soldier (uncredited)',
  'credit_id': '52fe48019251416c750acb43',
  'gender': 0,
  'id': 1207287,
  'name': 'Kai Pantano',
  'order': 71},
 {'cast_id': 92,
  'character': 'Blast Technician (uncredited)',
  'credit_id': '52fe48019251416c750acb47',
  'gender': 0,
  'id': 1207288,
  'name': 'Logan Pithyou',
  'order': 72},
 {'cast_id': 93,
  'character': 'Vindum Raah (uncredited)',
  'credit_id': '52fe48019251416c750acb4b',
  'gender': 0,
  'id': 1207289,
  'name': 'Stuart Pollock',
  'order': 73},
 {'cast_id': 94,
  'character': 'Hero (uncredited)',
  'credit_id': '52fe48019251416c750acb4f',
  'gender': 0,
  'id': 584868,
  'name': 'Raja',
  'order': 74},
 {'cast_id': 95,
  'character': 'Ops Centreworker (uncredited)',
  'credit_id': '52fe48019251416c750acb53',
  'gender': 0,
  'id': 1207290,
  'name': 'Gareth Ruck',
  'order': 75},
 {'cast_id': 96,
  'character': 'Engineer (uncredited)',
  'credit_id': '52fe48019251416c750acb57',
  'gender': 0,
  'id': 1062463,
  'name': 'Rhian Sheehan',
  'order': 76},
 {'cast_id': 97,
  'character': "Col. Quaritch's Mech Suit (uncredited)",
  'credit_id': '52fe48019251416c750acb5b',
  'gender': 0,
  'id': 60656,
  'name': 'T. J. Storm',
  'order': 77},
 {'cast_id': 98,
  'character': 'Female Marine (uncredited)',
  'credit_id': '52fe48019251416c750acb5f',
  'gender': 0,
  'id': 1207291,
  'name': 'Jodie Taylor',
  'order': 78},
 {'cast_id': 99,
  'character': 'Ikran Clan Leader (uncredited)',
  'credit_id': '52fe48019251416c750acb63',
  'gender': 1,
  'id': 1186027,
  'name': 'Alicia Vela-Bailey',
  'order': 79},
 {'cast_id': 100,
  'character': 'Geologist (uncredited)',
  'credit_id': '52fe48019251416c750acb67',
  'gender': 0,
  'id': 1207292,
  'name': 'Richard Whiteside',
  'order': 80},
 {'cast_id': 101,
  'character': "Na'vi (uncredited)",
  'credit_id': '52fe48019251416c750acb6b',
  'gender': 0,
  'id': 103259,
  'name': 'Nikie Zambo',
  'order': 81},
 {'cast_id': 102,
  'character': 'Ambient Room Tech / Troupe',
  'credit_id': '52fe48019251416c750acb6f',
  'gender': 1,
  'id': 42286,
  'name': 'Julene Renee',
  'order': 82}]

In [37]:
def convert3(obj):
    for i in ast.literal_eval(obj):
        lst = []
        counter = 0
        if counter != 3:
            lst.append(i['name'])
            counter+=1
        else:
            break
        return lst

In [38]:
movies['cast'].apply(convert3)

0       [Sam Worthington]
1           [Johnny Depp]
2          [Daniel Craig]
3        [Christian Bale]
4         [Taylor Kitsch]
              ...
4791    [Carlos Gallardo]
4792       [Edward Burns]
4793        [Eric Mabius]
4794      [Daniel Henney]
4795     [Drew Barrymore]
Name: cast, Length: 4793, dtype: object

In [39]:
movies['cast'] = movies['cast'].apply(convert3)

In [40]:
movies['crew'][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [41]:
def fetch_director(obj):
    for i in ast.literal_eval(obj):
        lst = []
        if i['job'] == 'Director':
            lst.append(i['name'])
        return lst

In [42]:
movies['crew'].apply(fetch_director)

0                       []
1                       []
2                       []
3                       []
4                       []
               ...
4791    [Robert Rodriguez]
4792        [Edward Burns]
4793                    []
4794         [Daniel Hsia]
4795                    []
Name: crew, Length: 4793, dtype: object

In [43]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [44]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...",[Action],[culture clash],[Sam Worthington],[]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",[Adventure],[ocean],[Johnny Depp],[]
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,[Action],[spy],[Daniel Craig],[]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,[Action],[dc comics],[Christian Bale],[]
4,49529,John Carter,"John Carter is a war-weary, former military ca...",[Action],[based on novel],[Taylor Kitsch],[]

In [45]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [46]:
movies['overview'].apply(lambda x:x.split())

0       [In, the, 22nd, century,, a, paraplegic, Marin...
1       [Captain, Barbossa,, long, believed, to, be, d...
2       [A, cryptic, message, from, Bondâ€™s, past, send...
3       [Following, the, death, of, District, Attorney...
4       [John, Carter, is, a, war-weary,, former, mili...
                              ...
4791    [El, Mariachi, just, wants, to, play, his, gui...
4792    [A, newlywed, couple's, honeymoon, is, upended...
4793    ["Signed,, Sealed,, Delivered", introduces, a,...
4794    [When, ambitious, New, York, attorney, Sam, is...
4795    [Ever, since, the, second, grade, when, he, fi...
Name: overview, Length: 4793, dtype: object

In [47]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [48]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...",[Action],[culture clash],[Sam Worthington],[]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...",[Adventure],[ocean],[Johnny Depp],[]
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...",[Action],[spy],[Daniel Craig],[]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...",[Action],[dc comics],[Christian Bale],[]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...",[Action],[based on novel],[Taylor Kitsch],[]

In [49]:
def replace_space(obj):
    x = movies['genres']
    x1 = x
    for i in x:
        if i == " ":
            x1 = x1.replace(i, "")
    return x1

In [50]:
movies['genres'].shape

(4793,)

In [51]:
movies['genres'].apply(replace_space)

,0,1,2,3,4,5,6,7,8,9,...,4786,4787,4788,4789,4790,4791,4792,4793,4794,4795
0,[Action],[Adventure],[Action],[Action],[Action],[Fantasy],[Animation],[Action],[Adventure],[Action],...,[Drama],[Thriller],[Drama],[Science Fiction],[Foreign],[Action],[Comedy],[Comedy],None,[Documentary]
1,[Action],[Adventure],[Action],[Action],[Action],[Fantasy],[Animation],[Action],[Adventure],[Action],...,[Drama],[Thriller],[Drama],[Science Fiction],[Foreign],[Action],[Comedy],[Comedy],None,[Documentary]
2,[Action],[Adventure],[Action],[Action],[Action],[Fantasy],[Animation],[Action],[Adventure],[Action],...,[Drama],[Thriller],[Drama],[Science Fiction],[Foreign],[Action],[Comedy],[Comedy],None,[Documentary]
3,[Action],[Adventure],[Action],[Action],[Action],[Fantasy],[Animation],[Action],[Adventure],[Action],...,[Drama],[Thriller],[Drama],[Science Fiction],[Foreign],[Action],[Comedy],[Comedy],None,[Documentary]
4,[Action],[Adventure],[Action],[Action],[Action],[Fantasy],[Animation],[Action],[Adventure],[Action],...,[Drama],[Thriller],[Drama],[Science Fiction],[Foreign],[Action],[Comedy],[Comedy],None,[Documentary]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4791,[Action],[Adventure],[Action],[Action],[Action],[Fantasy],[Animation],[Action],[Adventure],[Action],...,[Drama],[Thriller],[Drama],[Science Fiction],[Foreign],[Action],[Comedy],[Comedy],None,[Documentary]
4792,[Action],[Adventure],[Action],[Action],[Action],[Fantasy],[Animation],[Action],[Adventure],[Action],...,[Drama],[Thriller],[Drama],[Science Fiction],[Foreign],[Action],[Comedy],[Comedy],None,[Documentary]
4793,[Action],[Adventure],[Action],[Action],[Action],[Fantasy],[Animation],[Action],[Adventure],[Action],...,[Drama],[Thriller],[Drama],[Science Fiction],[Foreign],[Action],[Comedy],[Comedy],None,[Documentary]
4794,[Action],[Adventure],[Action],[Action],[Action],[Fantasy],[Animation],[Action],[Adventure],[Action],...,[Drama],[Thriller],[Drama],[Science Fiction],[Foreign],[Action],[Comedy],[Comedy],None,[Documentary]
4795,[Action],[Adventure],[Action],[Action],[Action],[Fantasy],[Animation],[Action],[Adventure],[Action],...,[Drama],[Thriller],[Drama],[Science Fiction],[Foreign],[Action],[Comedy],[Comedy],None,[Documentary]

In [52]:
movies['genres'].apply(lambda x: [i.replace(" ", "") if i else "" for i in x] if x else [])

0            [Action]
1         [Adventure]
2            [Action]
3            [Action]
4            [Action]
            ...
4791         [Action]
4792         [Comedy]
4793         [Comedy]
4794               []
4795    [Documentary]
Name: genres, Length: 4793, dtype: object

In [53]:
movies['generes'] = movies['genres'] = movies['genres'].apply(lambda x: [i.replace(" ", "") if i else "" for i in x] if x else [])

In [54]:
movies['genres'].head(50)

0             [Action]
1          [Adventure]
2             [Action]
3             [Action]
4             [Action]
5            [Fantasy]
6          [Animation]
7             [Action]
8          [Adventure]
9             [Action]
10         [Adventure]
11         [Adventure]
12         [Adventure]
13            [Action]
14            [Action]
15         [Adventure]
16    [ScienceFiction]
17         [Adventure]
18            [Action]
19            [Action]
20            [Action]
21            [Action]
22         [Adventure]
23         [Adventure]
24         [Adventure]
25             [Drama]
26         [Adventure]
27          [Thriller]
28            [Action]
29            [Action]
30            [Action]
31            [Action]
32            [Family]
33         [Adventure]
34         [Animation]
35    [ScienceFiction]
36    [ScienceFiction]
37           [Fantasy]
38            [Action]
39         [Adventure]
40         [Animation]
41         [Adventure]
42         [Animation]
43            [Action]
44            [Action]
45            [Action]
46            [Action]
47            [Action]
48            [Action]
49             [Drama]
Name: genres, dtype: object

In [55]:
movies['cast'] = movies['cast'].apply(lambda x: [i.replace(" ", "") if i else "" for i in x] if x else [])
movies['keywords'] = movies['keywords'].apply(lambda x: [i.replace(" ", "") if i else "" for i in x] if x else [])
movies['title'] = movies['title'].apply(lambda x: [i.replace(" ", "") if i else "" for i in x] if x else [])

In [56]:
movies.head(50)

,movie_id,title,overview,genres,keywords,cast,crew,generes
0,19995,"[A, v, a, t, a, r]","[In, the, 22nd, century,, a, paraplegic, Marin...",[Action],[cultureclash],[SamWorthington],[],[Action]
1,285,"[P, i, r, a, t, e, s, , o, f, , t, h, e, , C, ...","[Captain, Barbossa,, long, believed, to, be, d...",[Adventure],[ocean],[JohnnyDepp],[],[Adventure]
2,206647,"[S, p, e, c, t, r, e]","[A, cryptic, message, from, Bondâ€™s, past, send...",[Action],[spy],[DanielCraig],[],[Action]
3,49026,"[T, h, e, , D, a, r, k, , K, n, i, g, h, t, , ...","[Following, the, death, of, District, Attorney...",[Action],[dccomics],[ChristianBale],[],[Action]
4,49529,"[J, o, h, n, , C, a, r, t, e, r]","[John, Carter, is, a, war-weary,, former, mili...",[Action],[basedonnovel],[TaylorKitsch],[],[Action]
5,559,"[S, p, i, d, e, r, -, M, a, n, , 3]","[The, seemingly, invincible, Spider-Man, goes,...",[Fantasy],[dualidentity],[TobeyMaguire],[],[Fantasy]
6,38757,"[T, a, n, g, l, e, d]","[When, the, kingdom's, most, wanted-and, most,...",[Animation],[hostage],[ZacharyLevi],[],[Animation]
7,99861,"[A, v, e, n, g, e, r, s, :, , A, g, e, , o, f,...","[When, Tony, Stark, tries, to, jumpstart, a, d...",[Action],[marvelcomic],[RobertDowneyJr.],[],[Action]
8,767,"[H, a, r, r, y, , P, o, t, t, e, r, , a, n, d,...","[As, Harry, begins, his, sixth, year, at, Hogw...",[Adventure],[witch],[DanielRadcliffe],[],[Adventure]
9,209112,"[B, a, t, m, a, n, , v, , S, u, p, e, r, m, a,...","[Fearing, the, actions, of, a, god-like, Super...",[Action],[dccomics],[BenAffleck],[],[Action]
10,1452,"[S, u, p, e, r, m, a, n, , R, e, t, u, r, n, s]","[Superman, returns, to, discover, his, 5-year,...",[Adventure],[savingtheworld],[BrandonRouth],[],[Adventure]
11,10764,"[Q, u, a, n, t, u, m, , o, f, , S, o, l, a, c, e]","[Quantum, of, Solace, continues, the, adventur...",[Adventure],[killing],[DanielCraig],[],[Adventure]
12,58,"[P, i, r, a, t, e, s, , o, f, , t, h, e, , C, ...","[Captain, Jack, Sparrow, works, his, way, out,...",[Adventure],[witch],[JohnnyDepp],[],[Adventure]
13,57201,"[T, h, e, , L, o, n, e, , R, a, n, g, e, r]","[The, Texas, Rangers, chase, down, a, gang, of...",[Action],[texas],[JohnnyDepp],[Gore Verbinski],[Action]
14,49521,"[M, a, n, , o, f, , S, t, e, e, l]","[A, young, boy, learns, that, he, has, extraor...",[Action],[savingtheworld],[HenryCavill],[],[Action]
15,2454,"[T, h, e, , C, h, r, o, n, i, c, l, e, s, , o,...","[One, year, after, their, incredible, adventur...",[Adventure],[basedonnovel],[BenBarnes],[],[Adventure]
16,24428,"[T, h, e, , A, v, e, n, g, e, r, s]","[When, an, unexpected, enemy, emerges, and, th...",[ScienceFiction],[newyork],[RobertDowneyJr.],[],[ScienceFiction]
17,1865,"[P, i, r, a, t, e, s, , o, f, , t, h, e, , C, ...","[Captain, Jack, Sparrow, crosses, paths, with,...",[Adventure],[sea],[JohnnyDepp],[],[Adventure]
18,41154,"[M, e, n, , i, n, , B, l, a, c, k, , 3]","[Agents, J, (Will, Smith), and, K, (Tommy, Lee...",[Action],[timetravel],[WillSmith],[],[Action]
19,122917,"[T, h, e, , H, o, b, b, i, t, :, , T, h, e, , ...","[Immediately, after, the, events, of, The, Des...",[Action],[corruption],[MartinFreeman],[],[Action]
20,1930,"[T, h, e, , A, m, a, z, i, n, g, , S, p, i, d,...","[Peter, Parker, is, an, outcast, high, schoole...",[Action],[lossoffather],[AndrewGarfield],[],[Action]
21,20662,"[R, o, b, i, n, , H, o, o, d]","[When, soldier, Robin, happens, upon, the, dyi...",[Action],[robinhood],[RussellCrowe],[],[Action]
22,57158,"[T, h, e, , H, o, b, b, i, t, :, , T, h, e, , ...","[The, Dwarves,, Bilbo, and, Gandalf, have, suc...",[Adventure],[elves],[MartinFreeman],[],[Adventure]
23,2268,"[T, h, e, , G, o, l, d, e, n, , C, o, m, p, a,...","[After, overhearing, a, shocking, secret,, pre...",[Adventure],[england],[DakotaBlueRichards],[],[Adventure]
24,254,"[K, i, n, g, , K, o, n, g]","[In, 1933, New, York,, an, overly, ambitious, ...",[Adventure],[filmbusiness],[NaomiWatts],[],[Adventure]
25,597,"[T, i, t, a, n, i, c]","[84, years, later,, a, 101-year-old, woman, na...",[Drama],[shipwreck],[KateWinslet],[],[Drama]
26,271110,"[C, a, p, t, a, i, n, , A, m, e, r, i, c, a, :...","[Following, the, events, of, Age, of, Ultron,,...",[Adventure],[civilwar],[ChrisEvans],[],[Adventure]
27,44833,"[B, a, t, t, l, e, s, h, i, p]","[When, mankind, beams, a, radio, signal, into,...",[Thriller],[fight],[TaylorKitsch],[],[Thriller]
28,135397,"[J, u, r, a, s, s, i, c, , W, o, r, l, d]","[Twenty-two, years, after, the, events, of, Ju...",[Action],[monster],[ChrisPratt],[],[Action]
29,37724,"[S, k, y, f, a, l, l]","[When, Bond's, latest, assignment, goes, grave...",[Action],[spy],[DanielCraig],[],[Action]
30,558,"[S, p, i, d, e, r, -, M, a, n, , 2]","[Peter, Parker, is, going, through, a, major, ...",[Action],[dualidentity],[TobeyMaguire],[],[Action]
31,68721,"[I, r, o, n, , M, a, n, , 3]","[When, Tony, Stark's, world, is, torn, apart, ...",[Action],[terrorist],[RobertDowneyJr.],[],[Action]
32,12155,"[A, l, i, c, e, , i, n, , W, o, n, d, e, r, l,...","[Alice,, an, unpretentious, and, individual, 1...",[Family],[basedonnovel],[MiaWasikowska],[],[Family]
33,36668,"[X, -, M, e, n, :, , T, h, e, , L, a, s, t, , ...","[When, a, cure, is, found, to, treat, mutation...",[Adventure],[mutant],[HughJackman],[],[Adventure]
34,62211,"[M, o, n, s, t, e, r, s, , U, n, i, v, e, r, s...","[A, look, at, the, relationship, between, Mike...",[Animation],[monster],[BillyCrystal],[],[Animation]
35,8373,"[T, r, a, n, s, f, o, r, m, e, r, s, :, , R, e...","[Sam, Witwicky, leaves, the, Autobots, behind,...",[ScienceFiction],[egypt],[ShiaLaBeouf],[],[ScienceFiction]
36,91314,"[T, r, a, n, s, f, o, r, m, e, r, s, :, , A, g...","[As, humanity, picks, up, the, pieces,, follow...",[ScienceFiction],[sequel],[MarkWahlberg],[],[ScienceFiction]
37,68728,"[O, z, :, , T, h, e, , G, r, e, a, t, , a, n, ...","[Oscar, Diggs,, a, small-time, circus, illusio...",[Fantasy],[circus],[JamesFranco],[],[Fantasy]
38,102382,"[T, h, e, , A, m, a, z, i, n, g, , S, p, i, d,...","[For, Peter, Parker,, life, is, busy., Between...",[Action],[obsession],[AndrewGarfield],[],[Action]
39,20526,"[T, R, O, N, :, , L, e, g, a, c, y]","[Sam, Flynn,, the, tech-savvy, and, daring, so...",[Adventure],[artificialintelligence],[GarrettHedlund],[],[Adventure]
40,49013,"[C, a, r, s, , 2]","[Star, race, car, Lightning, McQueen, and, his...",[Animation],[carrace],[OwenWilson],[John Lasseter],[Animation]
41,44912,"[G, r, e, e, n, , L, a, n, t, e, r, n]","[For, centuries,, a, small, but, powerful, for...",[Adventure],[dccomics],[RyanReynolds],[],[Adventure]
42,10193,"[T, o, y, , S, t, o, r, y, , 3]","[Woody,, Buzz,, and, the, rest, of, Andy's, to...",[Animation],[hostage],[TomHanks],[],[Animation]
43,534,"[T, e, r, m, i, n, a, t, o, r, , S, a, l, v, a...","[All, grown, up, in, post-apocalyptic, 2018,, ...",[Action],[savingtheworld],[ChristianBale],[],[Action]
44,168259,"[F, u, r, i, o, u, s, , 7]","[Deckard, Shaw, seeks, revenge, against, Domin...",[Action],[carrace],[VinDiesel],[James Wan],[Action]
45,72190,"[W, o, r, l, d, , W, a, r, , Z]","[Life, for, former, United, Nations, investiga...",[Action],[dystopia],[BradPitt],[],[Action]
46,127585,"[X, -, M, e, n, :, , D, a, y, s, , o, f, , F, ...","[The, ultimate, X-Men, ensemble, fights, a, wa...",[Action],[1970s],[HughJackman],[],[Action]
47,54138,"[S, t, a, r, , T, r, e, k, , I, n, t, o, , D, ...","[When, the, crew, of, the, Enterprise, is, cal...",[Action],[spacecraft],[ChrisPine],[],[Action]
48,81005,"[J, a, c, k, , t, h, e, , G, i, a, n, t, , S, ...","[The, story, of, an, ancient, war, that, is, r...",[Action],[basedonfairytale],[NicholasHoult],[],[Action]
49,64682,"[T, h, e, , G, r, e, a, t, , G, a, t, s, b, y]","[An, adaptation, of, F., Scott, Fitzgerald's, ...",[Drama],[basedonnovel],[LeonardoDiCaprio],[],[Drama]

In [57]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,generes
0,19995,"[A, v, a, t, a, r]","[In, the, 22nd, century,, a, paraplegic, Marin...",[Action],[cultureclash],[SamWorthington],[],[Action]
1,285,"[P, i, r, a, t, e, s, , o, f, , t, h, e, , C, ...","[Captain, Barbossa,, long, believed, to, be, d...",[Adventure],[ocean],[JohnnyDepp],[],[Adventure]
2,206647,"[S, p, e, c, t, r, e]","[A, cryptic, message, from, Bondâ€™s, past, send...",[Action],[spy],[DanielCraig],[],[Action]
3,49026,"[T, h, e, , D, a, r, k, , K, n, i, g, h, t, , ...","[Following, the, death, of, District, Attorney...",[Action],[dccomics],[ChristianBale],[],[Action]
4,49529,"[J, o, h, n, , C, a, r, t, e, r]","[John, Carter, is, a, war-weary,, former, mili...",[Action],[basedonnovel],[TaylorKitsch],[],[Action]

In [58]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [59]:
movies.head(10)

,movie_id,title,overview,genres,keywords,cast,crew,generes,tags
0,19995,"[A, v, a, t, a, r]","[In, the, 22nd, century,, a, paraplegic, Marin...",[Action],[cultureclash],[SamWorthington],[],[Action],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,"[P, i, r, a, t, e, s, , o, f, , t, h, e, , C, ...","[Captain, Barbossa,, long, believed, to, be, d...",[Adventure],[ocean],[JohnnyDepp],[],[Adventure],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,"[S, p, e, c, t, r, e]","[A, cryptic, message, from, Bondâ€™s, past, send...",[Action],[spy],[DanielCraig],[],[Action],"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,"[T, h, e, , D, a, r, k, , K, n, i, g, h, t, , ...","[Following, the, death, of, District, Attorney...",[Action],[dccomics],[ChristianBale],[],[Action],"[Following, the, death, of, District, Attorney..."
4,49529,"[J, o, h, n, , C, a, r, t, e, r]","[John, Carter, is, a, war-weary,, former, mili...",[Action],[basedonnovel],[TaylorKitsch],[],[Action],"[John, Carter, is, a, war-weary,, former, mili..."
5,559,"[S, p, i, d, e, r, -, M, a, n, , 3]","[The, seemingly, invincible, Spider-Man, goes,...",[Fantasy],[dualidentity],[TobeyMaguire],[],[Fantasy],"[The, seemingly, invincible, Spider-Man, goes,..."
6,38757,"[T, a, n, g, l, e, d]","[When, the, kingdom's, most, wanted-and, most,...",[Animation],[hostage],[ZacharyLevi],[],[Animation],"[When, the, kingdom's, most, wanted-and, most,..."
7,99861,"[A, v, e, n, g, e, r, s, :, , A, g, e, , o, f,...","[When, Tony, Stark, tries, to, jumpstart, a, d...",[Action],[marvelcomic],[RobertDowneyJr.],[],[Action],"[When, Tony, Stark, tries, to, jumpstart, a, d..."
8,767,"[H, a, r, r, y, , P, o, t, t, e, r, , a, n, d,...","[As, Harry, begins, his, sixth, year, at, Hogw...",[Adventure],[witch],[DanielRadcliffe],[],[Adventure],"[As, Harry, begins, his, sixth, year, at, Hogw..."
9,209112,"[B, a, t, m, a, n, , v, , S, u, p, e, r, m, a,...","[Fearing, the, actions, of, a, god-like, Super...",[Action],[dccomics],[BenAffleck],[],[Action],"[Fearing, the, actions, of, a, god-like, Super..."

In [60]:
new_movies = movies[['movie_id','title','tags']]

In [61]:
new_movies.head()

,movie_id,title,tags
0,19995,"[A, v, a, t, a, r]","[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,"[P, i, r, a, t, e, s, , o, f, , t, h, e, , C, ...","[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,"[S, p, e, c, t, r, e]","[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,"[T, h, e, , D, a, r, k, , K, n, i, g, h, t, , ...","[Following, the, death, of, District, Attorney..."
4,49529,"[J, o, h, n, , C, a, r, t, e, r]","[John, Carter, is, a, war-weary,, former, mili..."

In [62]:
new_movies['tags'] = new_movies['tags'].apply(lambda x: " ".join(map(str, x)) if isinstance(x, (list, tuple)) else str(x))

/tmp/ipykernel_26420/4274200253.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_movies['tags'] = new_movies['tags'].apply(lambda x: " ".join(map(str, x)) if isinstance(x, (list, tuple)) else str(x))

In [63]:
new_movies.head()

,movie_id,title,tags
0,19995,"[A, v, a, t, a, r]","In the 22nd century, a paraplegic Marine is di..."
1,285,"[P, i, r, a, t, e, s, , o, f, , t, h, e, , C, ...","Captain Barbossa, long believed to be dead, ha..."
2,206647,"[S, p, e, c, t, r, e]",A cryptic message from Bondâ€™s past sends him o...
3,49026,"[T, h, e, , D, a, r, k, , K, n, i, g, h, t, , ...",Following the death of District Attorney Harve...
4,49529,"[J, o, h, n, , C, a, r, t, e, r]","John Carter is a war-weary, former military ca..."

In [64]:
new_movies['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action cultureclash SamWorthington'

In [65]:
new_movies['tags'].apply(lambda x:x.lower())

0       in the 22nd century, a paraplegic marine is di...
1       captain barbossa, long believed to be dead, ha...
2       a cryptic message from bondâ€™s past sends him o...
3       following the death of district attorney harve...
4       john carter is a war-weary, former military ca...
                              ...
4791    el mariachi just wants to play his guitar and ...
4792    a newlywed couple's honeymoon is upended by th...
4793    "signed, sealed, delivered" introduces a dedic...
4794    when ambitious new york attorney sam is sent t...
4795    ever since the second grade when he first saw ...
Name: tags, Length: 4793, dtype: object

In [66]:
new_movies['tags'] = new_movies['tags'].apply(lambda x:x.lower())

/tmp/ipykernel_26420/1627240426.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_movies['tags'] = new_movies['tags'].apply(lambda x:x.lower())

In [67]:
new_movies.head()

,movie_id,title,tags
0,19995,"[A, v, a, t, a, r]","in the 22nd century, a paraplegic marine is di..."
1,285,"[P, i, r, a, t, e, s, , o, f, , t, h, e, , C, ...","captain barbossa, long believed to be dead, ha..."
2,206647,"[S, p, e, c, t, r, e]",a cryptic message from bondâ€™s past sends him o...
3,49026,"[T, h, e, , D, a, r, k, , K, n, i, g, h, t, , ...",following the death of district attorney harve...
4,49529,"[J, o, h, n, , C, a, r, t, e, r]","john carter is a war-weary, former military ca..."

In [68]:
new_movies['title'][0]

['A', 'v', 'a', 't', 'a', 'r']

In [69]:
new_movies['title'] = new_movies['title'].apply(lambda x: "".join(map(str, x)) if isinstance(x, (list, tuple)) else str(x))

/tmp/ipykernel_26420/2882604469.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_movies['title'] = new_movies['title'].apply(lambda x: "".join(map(str, x)) if isinstance(x, (list, tuple)) else str(x))

In [70]:
new_movies.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,PiratesoftheCaribbean:AtWorld'sEnd,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bondâ€™s past sends him o...
3,49026,TheDarkKnightRises,following the death of district attorney harve...
4,49529,JohnCarter,"john carter is a war-weary, former military ca..."

In [71]:
new_movies['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action cultureclash samworthington'

In [72]:
new_movies['tags'][1]

'captain barbossa, long believed to be dead, has come back to life and is headed to the edge of the earth with will turner and elizabeth swann. but nothing is quite as it seems. adventure ocean johnnydepp'

In [73]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [74]:
vectors = cv.fit_transform(new_movies['tags']).toarray()

In [75]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [76]:
new_movies.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,PiratesoftheCaribbean:AtWorld'sEnd,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bondâ€™s past sends him o...
3,49026,TheDarkKnightRises,following the death of district attorney harve...
4,49529,JohnCarter,"john carter is a war-weary, former military ca..."

In [77]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0])

In [78]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zombies', 'zone', 'zoo'], dtype=object)

In [79]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zombies', 'zone', 'zoo'], dtype=object)

In [80]:
!pip install nltk

Requirement already satisfied: nltk in /home/dhruv/.local/lib/python3.8/site-packages (3.8.1)
Requirement already satisfied: regex>=2021.8.3 in /home/dhruv/.local/lib/python3.8/site-packages (from nltk) (2023.12.25)
Requirement already satisfied: joblib in /home/dhruv/.local/lib/python3.8/site-packages (from nltk) (1.3.2)
Requirement already satisfied: click in /usr/lib/python3/dist-packages (from nltk) (7.0)
Requirement already satisfied: tqdm in /home/dhruv/.local/lib/python3.8/site-packages (from nltk) (4.66.1)

In [81]:
import nltk

In [82]:
from nltk.stem.porter import PorterStemmer

In [83]:
ps = PorterStemmer

In [84]:
from nltk.stem import PorterStemmer
ps = PorterStemmer()

In [85]:
word = 'danced'
ps.stem(word)

'danc'

In [86]:
ps.stem('captain barbossa, long believed to be dead, has come back to life and is headed to the edge of the earth with will turner and elizabeth swann. but nothing is quite as it seems. adventure ocean johnnydepp')

'captain barbossa, long believed to be dead, has come back to life and is headed to the edge of the earth with will turner and elizabeth swann. but nothing is quite as it seems. adventure ocean johnnydepp'

In [87]:
def stem(word):
    y = []
    for i in word.split():
        y.append(ps.stem(i))
        return " ".join(y)

In [88]:
mew_movies = new_movies['tags'].apply(stem)

In [117]:
new_movies.head(20)

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,PiratesoftheCaribbean:AtWorld'sEnd,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bondâ€™s past sends him o...
3,49026,TheDarkKnightRises,following the death of district attorney harve...
4,49529,JohnCarter,"john carter is a war-weary, former military ca..."
5,559,Spider-Man3,the seemingly invincible spider-man goes up ag...
6,38757,Tangled,when the kingdom's most wanted-and most charmi...
7,99861,Avengers:AgeofUltron,when tony stark tries to jumpstart a dormant p...
8,767,HarryPotterandtheHalf-BloodPrince,"as harry begins his sixth year at hogwarts, he..."
9,209112,BatmanvSuperman:DawnofJustice,fearing the actions of a god-like super hero l...
10,1452,SupermanReturns,superman returns to discover his 5-year absenc...
11,10764,QuantumofSolace,quantum of solace continues the adventures of ...
12,58,PiratesoftheCaribbean:DeadMan'sChest,captain jack sparrow works his way out of a bl...
13,57201,TheLoneRanger,the texas rangers chase down a gang of outlaws...
14,49521,ManofSteel,a young boy learns that he has extraordinary p...
15,2454,TheChroniclesofNarnia:PrinceCaspian,one year after their incredible adventures in ...
16,24428,TheAvengers,when an unexpected enemy emerges and threatens...
17,1865,PiratesoftheCaribbean:OnStrangerTides,captain jack sparrow crosses paths with a woma...
18,41154,MeninBlack3,agents j (will smith) and k (tommy lee jones) ...
19,122917,TheHobbit:TheBattleoftheFiveArmies,immediately after the events of the desolation...

In [90]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zombies', 'zone', 'zoo'], dtype=object)

In [91]:
from sklearn.metrics.pairwise import cosine_similarity

In [92]:
cosine_similarity(vectors)

array([[1.        , 0.        , 0.05455447, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.        , ..., 0.04188539, 0.        ,
        0.        ],
       [0.05455447, 0.        , 1.        , ..., 0.03311331, 0.        ,
        0.        ],
       ...,
       [0.        , 0.04188539, 0.03311331, ..., 1.        , 0.05333807,
        0.05195243],
       [0.        , 0.        , 0.        , ..., 0.05333807, 1.        ,
        0.05264981],
       [0.        , 0.        , 0.        , ..., 0.05195243, 0.05264981,
        1.        ]])

In [93]:
similarity = cosine_similarity(vectors)

In [94]:
sorted(list(enumerate(similarity[0])),reverse=True,key = lambda x:x[1])[1:6]

[(3597, 0.27003086243366087),
 (151, 0.23904572186687872),
 (528, 0.20145574100634506),
 (311, 0.18609684207969418),
 (567, 0.18394180184548975)]

In [95]:
new_movies[new_movies['title']=='JohnCarter'].index[0]

4

In [126]:
def recommend(movie):
    movie_index = new_movies[new_movies['title'] == movie].index[0]
    distance = similarity[movie_index]
    movies_list = sorted(list(enumerate(distance)), reverse=True, key=lambda x: x[1])[1:6]
    
    for i in movies_list:
        print(new_movies.iloc[i[0]].title)

In [135]:
recommend('Batman')

Batman
TheDarkKnightRises
Batman&Robin
EnemyattheGates
BatmanBegins

In [102]:
new_movies.iloc[35

'Apollo18'

In [133]:
new_movies['title'][14]

'ManofSteel'